services:
  # --- ANGULAR FRONTEND (DEV) ---
  angular_frontend:
    container_name: angular_dev
    build:
      context: ./pumpkindesign_ssr
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ./pumpkindesign_ssr:/app
      - /app/node_modules
    command: npm run start
    environment:
      - WATCHPACK_POLLING=true
    env_file: ./strapi_pumpkindesign_ssr/.env
    networks:
      - strapi_net
    depends_on:
      - strapi

  # --- STRAPI BACKEND (DEV) ---
  strapi:
    container_name: strapi_dev
    build: ./strapi_pumpkindesign_ssr
    image: strapi:latest
    restart: unless-stopped
    env_file: ./strapi_pumpkindesign_ssr/.env
    volumes:
      - ./strapi_pumpkindesign_ssr/config:/opt/app/config
      - ./strapi_pumpkindesign_ssr/src:/opt/app/src
      - ./strapi_pumpkindesign_ssr/package.json:/opt/package.json
      - ./strapi_pumpkindesign_ssr/package-lock.json:/opt/package-lock.json
      - ./strapi_pumpkindesign_ssr/.env:/opt/app/.env
      - ./strapi_pumpkindesign_ssr/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi_net
    depends_on:
      strapiDB:
        condition: service_healthy
        
# --- PGADMIN (DEV) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_dev
    restart: unless-stopped
    env_file: ./strapi_pumpkindesign_ssr/.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - strapi_net
    depends_on:
      - strapiDB

  # --- POSTGRES DATENBANK ---
  strapiDB:
    container_name: strapiDB
    restart: unless-stopped
    image: postgres:16-alpine
    env_file: ./strapi_pumpkindesign_ssr/.env
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    networks:
      - strapi_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DATABASE_USERNAME} -d $${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  strapi-data:

networks:
  strapi_net:
    driver: bridge
