services:
  # --- ANGULAR FRONTEND ---
  angular_frontend:
    container_name: angular_prod
    build:
      context: ./pumpkindesign_ssr
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:4200:4200"
    env_file:
          - .env
    environment:
      - NODE_ENV=production
      - PORT=4200
    networks:
      - strapi_net
    depends_on:
      - strapi

  # --- STRAPI BACKEND ---
  strapi:
    container_name: strapi_prod
    build:
      context: ./strapi_pumpkindesign_ssr
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=strapiDB
      - DATABASE_PORT=5432
      - PORT=1337
    ports:
      - "127.0.0.1:1337:1337"
    networks:
      - strapi_net
    depends_on:
      strapiDB:
        condition: service_healthy

  # --- POSTGRES DATENBANK ---
  strapiDB:
    container_name: strapiDB
    restart: unless-stopped
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    networks:
      - strapi_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  strapi-data:

networks:
  strapi_net:
    driver: bridge