services:
  # --- ANGULAR FRONTEND (PROD / BFF) ---
  angular_frontend:
    container_name: angular_prod
    build:
      context: ./pumpkindesign_ssr
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "4200:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - STRAPI_API_TOKEN=${STRAPI_API_TOKEN}
    networks:
      - strapi_net
    depends_on:
      - strapi

  # --- STRAPI BACKEND (PROD) ---
  strapi:
    container_name: strapi_prod
    build:
      context: ./strapi_pumpkindesign_ssr
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: ./strapi_pumpkindesign_ssr/.env
    environment:
      - NODE_ENV=production
    volumes:
      - strapi-uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi_net
    depends_on:
      strapiDB:
        condition: service_healthy

  # --- POSTGRES DATENBANK (PROD) ---
  strapiDB:
    container_name: strapiDB_prod
    restart: unless-stopped
    image: postgres:16-alpine
    env_file: ./strapi_pumpkindesign_ssr/.env
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    networks:
      - strapi_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DATABASE_USERNAME} -d $${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  strapi-data:
  strapi-uploads:

networks:
  strapi_net:
    driver: bridge
