services:
  # --- ANGULAR FRONTEND (DEV) ---
  angular_frontend:
    container_name: angular_dev
    build:
      context: ./pumpkindesign_ssr
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ./pumpkindesign_ssr:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=4200
      - WATCHPACK_POLLING=true
      - BASE_PATH_STRAPI=http://pumpkin_api:3000
    command: npm run start
    networks:
      - strapi_net
    depends_on:
      - pumpkin_api

  # --- PUMPKIN API (DEV) ---
  pumpkin_api:
    container_name: pumpkin_api_dev
    build:
      context: ./pumpkin_api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./pumpkin_api:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - BASE_PATH_STRAPI=http://strapi:6466
    ports:
      - "3000:3000"
    networks:
      - strapi_net
    depends_on:
      - strapi

  # --- STRAPI BACKEND (DEV) ---
  strapi:
    container_name: strapi_dev
    build:
      context: ./strapi_pumpkindesign_ssr
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./strapi_pumpkindesign_ssr:/opt/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=strapiDB
      - DATABASE_PORT=5432
    ports:
      - "6466:6466"
    networks:
      - strapi_net
    depends_on:
      strapiDB:
        condition: service_healthy

  # --- PGADMIN (DEV) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - strapi_net
    depends_on:
      - strapiDB

  # --- POSTGRES DATENBANK ---
  strapiDB:
    container_name: strapiDB
    restart: unless-stopped
    env_file:
      - .env
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    networks:
      - strapi_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  strapi-data:

networks:
  strapi_net:
    driver: bridge
