# --- STAGE 1: Build ---
FROM node:24.16.0-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# --- STAGE 2: Run (Produktion) ---
FROM node:24.16.0-alpine AS production
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json ./
RUN npm ci --omit=dev
EXPOSE 4200
CMD ["node", "dist/pumpkindesign_ssr/server/server.mjs"]